language: python
python:
  - "pypy"
  - "2.7"
env:
  - HG_VERSION="3.4.2"
  - HG_VERSION="3.5.2"
  - HG_VERSION="3.6.3"
  - HG_VERSION="3.7.3"
  - HG_VERSION="3.8.2"
install:
  - pip install -r requirements.txt
  - pip install -U "mercurial==$HG_VERSION"
script: py.test --cov=hug
after_success: coveralls
